### ISSUE TITLE
Release Pine for Scala Native 0.4.0-M2

### ISSUE THREAD

**Issue by david-bouyssie** [sparsetech/pine#64]
Even if SN 0.4.0-M2 is a milestone, it is quite stable and now used as a target for several projects.
It would thus be great to consider to release a version of Pine compatible with this Scala Native version.

Thanks.

**Comment by tindzk** [comment]
At the moment, we only support stable releases which is why there is no Pine release for Scala.js 1.0 either. I am open to contributions that add support for more compiler versions (including Dotty), but I fear it is going to complicate the publishing process. Is there a way in sbt to target multiple Scala Native versions?

**Comment by david-bouyssie** [comment]
I think the only way for supporting multiple SN versions would be to have a specific branch for each specific SN version.

Another possibility is to drop the support for SN 0.3.x and switch directly to 0.4.0-M2. This is the choice made for scalatest for instance:
https://mvnrepository.com/artifact/org.scalatest/scalatest

**Comment by david-bouyssie** [comment]
After a short discussion with @ekrich on https://gitter.im/scala-native/scala-native the solution seems to use travis with the Sbt-CI-release plugin to configure env. variables for different builds. 
You can find usage example in this project https://github.com/ekrich/sconfig

Some interesting files:
https://github.com/ekrich/sconfig/blob/master/project/plugins.sbt
https://github.com/ekrich/sconfig/blob/master/.travis.yml

**Comment by tindzk** [comment]
I was thinking about this too, but I would prefer to avoid adding one more plug-in since the publishing process is already quite brittle.

My plan is to add publishing support to Seed in the near future that will allow us to build artefacts for multiple platform versions. Then, Pine will support Scala Native 0.4.0-M2 and also Scala.js 1.0.

**Comment by david-bouyssie** [comment]
Would be awesome :)

**Comment by ekrich** [comment]
@tindzk I don't know if you have seen this but there have been some improvements. https://medium.com/@taroleo/sbt-sonatype-f02bdafd78f1

So, `sbt-ci-release` is now using the above as a default. If you scroll down to the *Travis* area you can see some more info about Sonatype bundling. https://github.com/olafurpg/sbt-ci-release

You certainly don't need to use `sbt-ci-release` but that is the route I took as it would have been hard for me to figure out publishing on my own.

**Comment by david-bouyssie** [comment]
@ekrich this sonatype bundle API seems to be blazing fast!
Its availability in ```sbt-sonatype```  is a great step forward for the whole community.
